from typing import Protocol, Self, TypedDict

class _SSZObject(Protocol):
    @classmethod
    def from_ssz(cls, i: bytes) -> Self: ...
    @classmethod
    def from_json(cls, i: bytes) -> Self: ...
    def to_ssz(self) -> bytes: ...
    def to_json(self) -> bytes: ...

class BlockHeaderDict(TypedDict):
    slot: str
    proposer_index: str
    parent_root: str
    state_root: str
    body_root: str

# Mainnet classes
class ElectraSignedBeaconBlockMainnet(_SSZObject): ...

class ElectraBeaconBlockContentsMainnet(_SSZObject):
    def header_dict(self) -> BlockHeaderDict: ...
    def sign(self, signature: str) -> ElectraSignedBeaconBlockContentsMainnet: ...
    def block_hash_tree_root(self) -> str: ...

class ElectraSignedBeaconBlockContentsMainnet(_SSZObject): ...

class ElectraBlindedBeaconBlockMainnet(_SSZObject):
    def header_dict(self) -> BlockHeaderDict: ...
    def sign(self, signature: str) -> ElectraSignedBlindedBeaconBlockMainnet: ...
    def block_hash_tree_root(self) -> str: ...

class ElectraSignedBlindedBeaconBlockMainnet(_SSZObject): ...

# Minimal classes
class ElectraSignedBeaconBlockMinimal(_SSZObject): ...

class ElectraBeaconBlockContentsMinimal(_SSZObject):
    def header_dict(self) -> BlockHeaderDict: ...
    def sign(self, signature: str) -> ElectraSignedBeaconBlockContentsMinimal: ...
    def block_hash_tree_root(self) -> str: ...

class ElectraSignedBeaconBlockContentsMinimal(_SSZObject): ...

class ElectraBlindedBeaconBlockMinimal(_SSZObject):
    def header_dict(self) -> BlockHeaderDict: ...
    def sign(self, signature: str) -> ElectraSignedBlindedBeaconBlockMinimal: ...
    def block_hash_tree_root(self) -> str: ...

class ElectraSignedBlindedBeaconBlockMinimal(_SSZObject): ...

# Gnosis classes
class ElectraSignedBeaconBlockGnosis(_SSZObject): ...

class ElectraBeaconBlockContentsGnosis(_SSZObject):
    def header_dict(self) -> BlockHeaderDict: ...
    def sign(self, signature: str) -> ElectraSignedBeaconBlockContentsGnosis: ...
    def block_hash_tree_root(self) -> str: ...

class ElectraSignedBeaconBlockContentsGnosis(_SSZObject): ...

class ElectraBlindedBeaconBlockGnosis(_SSZObject):
    def header_dict(self) -> BlockHeaderDict: ...
    def sign(self, signature: str) -> ElectraSignedBlindedBeaconBlockGnosis: ...
    def block_hash_tree_root(self) -> str: ...

class ElectraSignedBlindedBeaconBlockGnosis(_SSZObject): ...

type ElectraBeaconBlockContentsType = (
    ElectraBeaconBlockContentsMainnet
    | ElectraBeaconBlockContentsGnosis
    | ElectraBeaconBlockContentsMinimal
)
type ElectraBlindedBeaconBlockType = (
    ElectraBlindedBeaconBlockMainnet
    | ElectraBlindedBeaconBlockGnosis
    | ElectraBlindedBeaconBlockMinimal
)
